### ISSUE TITLE
PR2 meshes showing up too dark

### ISSUE THREAD

**Issue by chapulina** [osrf/polymer-ros-rviz#3]
After following the example demo instructions, I get the PR2 to load but it looks too dark.

Using Collada Loader 1, this is what it looks like. Using Loader 2, all parts are black, so it's even worse.

![rvizpolymerpr2](https://user-images.githubusercontent.com/5751272/47888472-e0a45600-de01-11e8-8909-d038e5552e09.png)

The meshes look fine on `gzclient`. I tried ramping up the light on `ros3djs` but it didn't change the meshes.

Note that the issue is probably not coming from the code on this repo; it's most likely related to the meshes or the collada loader.

**Comment by iche033** [comment]
maybe you can try the [ColladaLoader](https://bitbucket.org/osrf/gzweb/src/default/gz3d/client/js/include/ColladaLoader.js) from gzweb

**Comment by chapulina** [comment]
So it seems that the problem is that [pr2_description](https://github.com/PR2/pr2_common/tree/melodic-devel/pr2_description) is using TIFF textures, which the collada loaders don't like, including GzWeb's:

![gzweb_tif](https://user-images.githubusercontent.com/5751272/48236640-012b5d80-e378-11e8-8838-49ce321150f7.png)

I manually converted a couple of the textures to png and confirmed that they work. The [PR2 SDF model at gazebo_models](https://bitbucket.org/osrf/gazebo_models/src/default/pr2/?at=default) uses PNG textures.

---

I'll close this issue since I don't think supporting TIFF should be a concern here. Here's an issue about getting rid of TIFFs at `pr2_description`: https://github.com/PR2/pr2_common/issues/226
